name: add-missing-predictions
on:
  schedule:
    - cron: "10,40 12-23 * * *"
jobs:
  add-missing-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Wait For Response
        uses: nev7n/wait_for_response@v1.0.1
        with:
          url: "https://www.desmondtwotwo.com/"
          responseCode: 200
          timeout: 10000
          interval: 2000
      - name: Hit endpoint
        env:
          SECRET: ${{ secrets.ACTIONS_SECRET }}
        run: |
          curl "https://www.desmondtwotwo.com/api/addMissingPredictions?secret=$SECRET"
