name: add-missing-predictions
on:
  # schedule:
  #   - cron: "10,40 12-23 * * *"
  workflow_dispatch:
jobs:
  add-missing-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Wait For Response
        uses: nev7n/wait_for_response@v1.0.1
        with:
          url: "https://www.desmondtwotwo.com/premierleague"
          responseCode: 200
          timeout: 15000
          interval: 1500
      - name: Hit endpoint
        env:
          SECRET: ${{ secrets.ACTIONS_SECRET }}
        run: |
          curl -X POST "https://www.desmondtwotwo.com/api/addMissingPredictions?secret=$SECRET"
