name: update-fixtures
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  updates-fixtures:
    runs-on: ubuntu-latest
    steps:
      - name: Hit endpoint
        env:
          SECRET: ${{ secrets.ACTIONS_SECRET }}
        run: |
          curl GET https://www.desmondtwotwo.com/api/populateFixtures?secret=$SECRET
