name: update-fixtures
on:
  # schedule:
  #   - cron: "5 7 * * *"
  workflow_dispatch:
jobs:
  updates-fixtures:
    runs-on: ubuntu-latest
    steps:
      - name: Hit endpoint
        env:
          SECRET: ${{ secrets.ACTIONS_SECRET }}
        run: |
          curl "https://www.desmondtwotwo.com/api/populateFixtures?numGameweeks=3&persist=true&secret=$SECRET"
